### ISSUE TITLE
MacOS Ventura service is not working with default package

### ISSUE THREAD

**Issue by luisnquin** [MatthewCroughan/NixThePlanet#26] opened 2024-03-19 00:59 UTC
I've been trying to install macOS ventura in my NixOS computer but the rebuild process failed due to apparently something's wrong with the macOS module, you can reproduce this error with the snippet of the image below

![image](https://github.com/MatthewCroughan/NixThePlanet/assets/86449787/0870b945-a85a-4424-8f44-c7cb18bcb7d1)

Here's the underlying error

![image](https://github.com/MatthewCroughan/NixThePlanet/assets/86449787/8d05f440-ca29-4681-b8bf-85b0a54085a5)

A workaround for me is to create the package directly from the flake itself.

![image](https://github.com/MatthewCroughan/NixThePlanet/assets/86449787/34b948a6-6d6a-4d2b-aee3-afb94f79fe8a)

![image](https://github.com/MatthewCroughan/NixThePlanet/assets/86449787/fc50ed06-28f3-4f6b-9a0f-861bc8525238)

Until then, everything else works as expected. I tried the macOS option and I want to say what you've been doing is great and it seems that it will save me a lot of money by saving me from buying a macOS just to do some app builds for iOS. :)

**Comment by MatthewCroughan** [comment] 2024-03-19 02:42
The nixosModule is tested in CI, there has to be something else going on in some code that you are not displaying in the screenshots, for example inside of `./system/configuration.nix`.

I notice you have `pkgs` defined since you are `inherit`ing it. Can you show me how you defined it?

**Comment by luisnquin** [comment] 2024-03-19 03:45
Here you can find some definitions that I have on my computer

 - [`pkgs` definition (flake)](https://github.com/luisnquin/nixos-config/blob/main/flake.nix)
 - [MacOS ventura service](https://github.com/luisnquin/nixos-config/blob/main/system/modules/vm/macos-ventura.nix)

Also, I don't think it's relevant but you can find the `mkSetup` definition [here](https://github.com/luisnquin/nixos-config/blob/main/lib/machine.nix)

The macOS module is disabled because I already used it and I don't wanted it to consume space until the next time

**Comment by luisnquin** [comment] 2024-03-19 03:50
You can find [this other configuration](https://github.com/INVERSIONESIO/nixos/blob/main/flake.nix) that I have used and got the same result, it is from a computer at my work that has NixOS installed and is not complex like my personal flake. In fact, the first two screenshots are from that computer.

**Comment by MatthewCroughan** [comment] 2024-03-19 19:14
@luisnquin I see you're applying a lot of overlays, and I think you're doing expressing something wrong and clobbering the overlay from this flake somehow. It is not easy to debug, but I hope this gives you something to go on.

**Comment by MatthewCroughan** [comment] 2024-03-19 19:25
Currently busy travelling, but I'll get back to this if you don't figure it out, when I get home again.

**Comment by luisnquin** [comment] 2024-03-19 19:47
Don't worry, I'm currently using the workaround I mentioned before. The issue might be when someone tries to start the service with the default package.

**Comment by MatthewCroughan** [comment] 2024-03-19 20:01
@luisnquin it definitely isn't that, because if you craft a barebones Nix flake without any of your code in it, this doesn't happen. The issue is in a nix expression you're including into your own config which includes other overlays. I'm fairly confident that it is your Nix code causing the problem at this time, having tested it myself. But debugging your config will be a bit time consuming for me right now, but I'm up for it when I get home.

**Comment by MatthewCroughan** [comment] 2024-05-10 05:40
Closing, as the issue cannot be reproduced and is likely an issue with the user's Nix expression, and not with the project.

**Closed** 2024-05-10 05:40 UTC
